### PR TITLE
Updated monk (common) and added Windwalker abilities

### PR DESCRIPTION
**Pull request by Blizz991**
See commit comments for testing

Will work on Retribution and Protection paladin next

### CODE REVIEW

**Comment by Blizz991** [comment]
Sorry for the 3 last commits, but the gitignore didn't include all the files necessary (I use Visual Studio 2017)

I reverted the commit, but would highly recommend the update in the 67819e6 commit to avoid similar issues in the future 👍

**Comment by mrkmcknz** [comment]
Honestly I think putting in the vscode stuff into the gitignore is a good move. Not sure how @JoshYaxley feels about putting it back in.

**Comment by JoshYaxley** [comment]
Thanks for this, Blizz - looks good!

We don't really need to include Spear Hand Strike at all, as interrupts currently get tracked anyway:



I think we can also use `"show": true` on a few more abilities, such as:

- Leg Sweep
- Paralysis
- Ring of Peace
- Diffuse Magic
- Xuen
- Serenity
- Touch of Karma

As for Touch of Karma, I'm not sure how important it is to show the target for this ability (or at least, not any more important than showing the target of most cooldowns).

I'm actually surprised that this gitignore isn't just the standard one I use which excludes loads of IDE specific things. I'll update it.

**Comment by Blizz991** [comment]
From what I could see, it only tracks when you _successfully_ interrupted something, I personally find it interesting to also find it interesting to see when they used their interrupt, but _didn't_ interrupt something :) - that was the idea behind it anyway, not sure if there's a better way to implement it though.

**Comment by JoshYaxley** [comment]
Feel free to make the commit yourself! I'm just here to help guide :)

**Comment by Blizz991** [comment]
Merged to make sure I had the last things (still new to working with git as a team, so please let me know if I messed something up there...) and updated the changes @JoshYaxley suggested.

Will start working on Retribution paladin now.

**Comment by Blizz991** [comment]
All commits from today need testing, will test once WCL is back online

**Comment by Blizz991** [comment]
Retribution and protection paladin checked using:
https://wipefest-dev.herokuapp.com/report/ykxNpCjLDFnJXR1W/fight/27?filters=R-0HCR02APMHMT0D,PALA-HJBLRPLHBPDI,PAPR-AWADGKSEBLALETBFBS,PARE-AWCREE,2064-0EHSUPAOFO0bEF0fFWLEPE0VCSHG0A&focuses=1,56

and

https://wipefest-dev.herokuapp.com/report/ykxNpCjLDFnJXR1W/fight/10?focuses=1,56
(I'm not sure if Protection paladin showing up here is intentional, there's no protection paladin in this part of the log? https://gyazo.com/2c6b5281bd2c0d900ca040ba7909774f)

(have a commit waiting to set Lay on Hands to `"showTarget":true`)

Need to find a log that uses CC to check the hunter stuff, will probably make one myself

**Comment by Blizz991** [comment]
Marksman hunter, Protection Paladin, Retribution paladin tested and working
https://wipefest-dev.herokuapp.com/report/hBnAz2Vr3JX9PwYT/fight/1?insights=2063-3&filters=R-0HCR02APMHMT0D,F-HEPPTMHS,HUNT-ATEXFTFA,HUMA-WSBSBA,2063-WOSTFRCA04BR1FEFMS0AFBMRFO0MBE&focuses=8

Beast Mastery and hunter (common) fully working as well:

https://wipefest-dev.herokuapp.com/report/Y3kQW4zCTab1gNVA/fight/29?focuses=30&filters=R-0HCR02APMHMT0D,F-HEPPTMHS,HUNT-ATEXFTFA,HUBE-INWSBSBABWAWTTMCST,2063-WOSTFRCA04BR1FEFMS0AFBMRFO0MBE

**Comment by JoshYaxley** [comment]
Just gone through them all and they look really good - great job! :D

**Comment by JoshYaxley** [comment]
I made a couple of small changes. The main thing is using `"friendly": true` and `"showSource": true` on Freezing Trap (Applied) and Binding Shot (Stunned) so that they appear on the left and also show the caster (in case there are several hunters):

**Pull request merged**
