### PR TITLE
Added core BrM defensive abilities

### PR DESCRIPTION
**Pull request by mrkmcknz**
Abilities added:

- Ironskin Brew
- Purifying Brew
- Fortifying Brew
- Black Ox Brew
- Dampen Harm
- Zen Meditation

### CODE REVIEW

**Comment by mrkmcknz** [comment]
Tested with the following logs: `rQKXpdWYhyxCc2fD` and `GP1zWKtRYQXJ4bkn`.

**Comment by JoshYaxley** [comment]
Thanks :) This looks good!

I think Blackout Combo might be bringing back too many events compared to the useful information it gives us.

We can also show some things by default with "show": "true": Things like Dampen Harm, Black Ox Brew, Fortifying Brew, and Zen Meditation.

Feel free to add some utility events too like Ring of Peace and Paralysis!
I need to get to work on a "general" file for each class to avoid repetition.

**Comment by JoshYaxley** [comment]
There is now a monk/monk.json file that can contain abilities that span all 3 specs :)

**Comment by mrkmcknz** [comment]
@JoshYaxley I'll take care of that tonight putting things in the monk.json and then remove Blackout Combo.

**Pull request merged**
