### PR TITLE
Feature/druid/feral guardian

### PR DESCRIPTION
**Pull request by mrkmcknz**
Added base Druid abilities along with specific abilities for Feral and Guardian.

### CODE REVIEW

**Comment by JoshYaxley** [comment]
Does Stampeding Roar need to be listed twice in `druid/druid.json`? Which specs have it available? Also the tags for Barkskin won't work - they can only have up to two tags (heading and subheading). Initially the tags were just going to be for any related words, but they became the headers for the filters so there's some limitations now.

**Comment by mrkmcknz** [comment]
Guardian Stampeding Roar is different to the base SR and in logs is recorded as a separate ability.

In regards to Barkskin, do you have a proposed solution in mind?

**Comment by JoshYaxley** [comment]
Want me to make these changes if I get some free time?

Stampeding Roar: can combine them both using `"ids": [123, 456]` instead of two event configs with `"id": 123` etc

Barkskin: Split it into 3 configs (one for each spec that has it) with tags `["druid", "restoration"]`, `["druid", "guardian"]`, `["druid", "balance"]`.

**Comment by JoshYaxley** [comment]
I made the changes and merged this into master (via develop - so you'll want to re-pull master to be up to date). I've enabled Guardian, but I assume that Feral still needs more work?

**Pull request merged**
