### PR TITLE
Aryssalis restod2

### PR DESCRIPTION
**Pull request by Aryssalis**
Sure, my reasoning for regrowth is that it should never really be cast outside of a clearcasting proc when it's free, otherwise it's MAJORLY inefficient. and wild growth has a 10 second cooldown, and also shouldn't be cast on cooldown, only in times of major damage kind of like a priest with holy word: sanctify, in fact it goes out less often than a priests holy priests prayer of healing which is tracked under the priest list.

https://wipefest-dev.herokuapp.com/report/JKt4BrhcdZWTbzkm/fight/13?focuses=2  
- mythic aggramar (8:08)

https://wipefest-dev.herokuapp.com/report/2GMTmNft4ZQw38yH/fight/15?focuses=3 
- mythic varimathras (4:07)

https://wipefest-dev.herokuapp.com/report/2GMTmNft4ZQw38yH/fight/11?focuses=3
- mythic kin'garoth (8:01)

### CODE REVIEW

**Comment by JoshYaxley** [comment]
Looks really good! Great job :)

I agree with your reasoning about Regrowth and Wild Growth.

I do think we can maybe use `"show": false` for Cenarion Ward and Efflorescence, as I imagine they are mostly used roughly on cooldown and their timing doesn't matter most of the time.

You can also show the target of Swiftmend using `"showTarget": true` like you have done with Ironbark.

Do we want to track Tree of Life? We can also track Innervate (I know there is already an event for it in `general/raid.json`. but if we provide one here we can use `"show": true` to force it to show by default).

Feel free to add some of the generic Druid abilities that apply to all 3 specs to the `druid/druid.json` file if you have any time (though I know there's a fair few: Roots, Mass Roots, Typhoon, Barkskin, Displacer Beast etc).

You could even track shapeshifting if you think that would be useful information!

**Comment by Aryssalis** [comment]
Incarnation: Tree of Life has been added as a buff to account for the random applications when casting wild growth to account for druids who choose to wear the legendary helmet.

Swiftmend now shows a target

Cenarion Ward is no longer set to show by default

Efflorescence is no longer set to show by default

Clearcasting buff and fade added for druids to see if they're using their regrowths during the proper window

I'm going to work on adding some druid talents to the druid section.

**Comment by Aryssalis** [comment]
Fixed an issue causing the removal of clearcasting, incarnation, and Essence of G'hanir to say "gains" instead of "loses".

**Comment by Aryssalis** [comment]
I've added the resto druids dispel to the list, and it shows the target dispelled, but I'm not sure how to get it to show the debuff that was dispelled, it functions fine now, but I'd like it to give more information.

**Comment by JoshYaxley** [comment]
This is looking really good!

I think Swiftmend needs "show*T*arget" instead of "show*t*arget" for it to work.

For the buff removed events, the convention is to append "(Removed)" to the name so that they are split into separate filters, for example:
* Essence of G'Hanir
* Essence of G'Hanir (Removed)

Then we can hide the removed event by default as people will be more interested in when it was first used (but still have access to the other information if necessary).

For the dispels, I need to do some work to create a proper **dispel** eventType. This would then have titles reading "X dispelled Y from Z". Feel free to post the idea here: https://ideas.wipefest.net/ :)

**Comment by JoshYaxley** [comment]
Looks great! I've removed Nature's Cure for now because I think when I implement it it will likely be a single event config that will work for all specs.

**Pull request merged**
